apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e2e7fzhnz-python
  janus-idp.io/tekton: e2e7fzhnz-python
  backstage.io/kubernetes-id: e2e7fzhnz-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e2e7fzhnz-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
